name: "Release Tools for bash"
description: "Sources the bash release tools in the targeted workflow."
author: "Mihai Bojin <mihai.bojin@gmail.com>"
inputs:
  version:
    description: "The version to install, defaults to the latest release"
    required: false
    default: "v0.0.4"

runs:
  using: "composite"
  steps:
    - name: Install the release tools
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
      run: ${{ github.action_path }}/scripts/action-install.sh