name: Build and Release

on:
  push:
    tags:
      - "v0.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build all modules
        run: scripts/build.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          make_latest: true
          files: |
            dist/all.bash
            dist/all.bash.sha256
