name: Build and Release Action

on:
  push:
    tags:
      - "v0.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the dist
        run: make all
        if: startsWith(github.ref, 'refs/tags/')

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          make_latest: true
          files: |
            dist/releasetools.bash
            dist/releasetools.bash.sha256
            dist/install.sh
            README.md
