name: Test Release

on:
  workflow_run:
    workflows: ["Build and Release Action"]
    types:
      - completed

jobs:
  test:
    name: Test GHA after release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v0.')
    steps:
      - uses: actions/checkout@v4

      - name: Extract release version
        shell: bash
        run: |
          GITHUB_REF='${{ github.ref }}'
          if [[ "$GITHUB_REF" =~ refs/tags/(v[0-9]+\..*) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "Found release version: $VERSION" >&2
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "No matching version found" >&2
            exit 1
          fi

      - name: "Install the latest release tools"
        uses: releasetools/bash@v0
        with:
          version: ${{ env.VERSION }}
        #env:
        #  RELEASETOOLS_INSTALL_DIR: /opt/hostedtoolcache/releasetools
        #  RELEASETOOLS_BINARY_DIR: ${{ env.HOME }}/bin

      - name: Ensure the release tools are installed and working
        shell: bash
        run: |
          rt base::version
          rt base::check_deps
